# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ServiceMan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ServiceMan
  pod 'Firebase'
  pod 'Firebase/Messaging'

  target 'ServiceMan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ServiceManTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ServiceMan-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ServiceMan-tvOS

end
